version: "3.3"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
      - MYSQL_DATABASE= 'achatdb'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: ghadaslimene/projetachat
    container_name: projetachat
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://172.17.0.3:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
#  projetachatfront:
#      image: ghadaslimene/projetachatfront
#      container_name: projetachatfront
#      links:
#        - app
#      depends_on:
#        - app
#      ports:
#        - 80:80
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: