version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'achatdb'

    ports:
      - "3306:3306"

  spring_app:
    image: achat
    container_name: achat
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
           "spring.datasource.username" : "root",
           "spring.datasource.password" : "root",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'

  achatfront:
    image: achatfront
    container_name: yousseftfifha/achatfront
    links:
      - spring_app
    depends_on:
      - spring_app
    ports:
      - 80:80

