version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'achatdb'
      # Password for root access
      MYSQL_ROOT_PASSWORD: ''
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

  spring-app:
    image: gahtanbensalman/achat
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jjdbc:mysql://localhost:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect