version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'achatdb'
      # Password for root access
      MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql


  spring-app:
    image: gahtanbensalman/achat
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.datasource.url"  : "jdbc:mysql://localhost:3306/achatdb?useSSL=false",
               "spring.datasource.username" : "root",
               "spring.datasource.password" : "",
               "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
               "spring.jpa.hibernate.ddl-auto" : "update"
             }'
    volumes:
      - .m2:/root/.m2